# Setup
title:               Álvaro Mañoso Oca
tagline:             'Software Architect Consultant'
description:         'Software Architect Consultant'
url:                 https://alvaromaoc.dev
baseurl:             ''

# About/contact
author:
  name:              Álvaro Mañoso Oca
  url:               https://linkedin.com/in/alvaro-manoso
  email:             me@alvaromaoc.dev

# Custom vars
version:             1.1.0
google_analytics_id: G-4QJERRX7SQ
